name: building ansible collection using custom build action and uploading artifacts
on: workflow_dispatch

jobs:
  create_ansible-folder:
    runs-on: ubuntu-latest
    name: Create ansible folder
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
        #with:
         #path: Ansible-Code
      # This step references the directory that contains the action
      - name: Use local build ansible collection action
        uses: ./.github/actions/build-ansible
      - name: upload the built ansible collection
        uses: actions/upload-artifact@v3
        with:
          name: ansible-collection
          path: ansible-local
      - name : download artifact
        uses: actions/download-artifact@v3
        with: 
           name: ansible-collection
           path: ansible-collection
      - name: Display structure of downloaded files
        run: ls -R

      
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          name: First-Release
          files: ansible-collection
          tag_name: first_tag
